# Generated by Django 5.1.5 on 2025-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_testdata_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='age',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
