# Generated by Django 5.1.5 on 2025-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='x',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
