# Generated by Django 5.1.5 on 2025-01-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_studentprofile_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='x',
        ),
    ]
