# Generated by Django 5.1.5 on 2025-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_studentprofile_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='teams',
            field=models.JSONField(db_index=True, default=list, null=True),
        ),
    ]
