# Generated by Django 5.1.5 on 2025-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(db_index=True, default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
