# Generated by Django 5.1.5 on 2025-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_studentprofile_first_name_studentprofile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LernzeitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lernzeit_ID', models.IntegerField(db_index=True, unique=True)),
                ('fach', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('art', models.IntegerField(db_index=True)),
                ('klasse', models.CharField(db_index=True, max_length=10, null=True)),
                ('stufen', models.JSONField(db_index=True)),
                ('tag', models.JSONField(db_index=True)),
                ('stunde', models.JSONField(db_index=True)),
                ('person', models.CharField(db_index=True, max_length=100)),
                ('raum', models.CharField(db_index=True, max_length=10)),
                ('plätze', models.IntegerField(db_index=True)),
                ('beschreibung', models.TextField()),
                ('activ', models.BooleanField(db_index=True)),
            ],
        ),
    ]
