# Generated by Django 5.1.5 on 2025-01-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_lernzeitprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lernzeitprofile',
            old_name='person',
            new_name='teacher_school_ID',
        ),
    ]
