# Generated by Django 5.1.5 on 2025-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_rename_person_lernzeitprofile_teacher_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
    ]
