# Generated by Django 5.1.5 on 2025-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_remove_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
