# Generated by Django 5.1.5 on 2025-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_alter_studentprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_ID',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
