# Generated by Django 5.1.5 on 2025-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_rename_art_lernzeitprofile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernzeitprofile',
            name='lernzeit_ID',
            field=models.IntegerField(db_index=True),
        ),
    ]
