# Generated by Django 5.1.5 on 2025-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_alter_lernzeitprofile_lernzeit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernzeitprofile',
            name='tag',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
