# Generated by Django 5.1.5 on 2025-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_lernzeitprofile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='beschreibung',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fächer',
            field=models.JSONField(db_index=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='kürzel',
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
        ),
    ]
