# Generated by Django 5.1.5 on 2025-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_studentprofile_beschreibung_studentprofile_fächer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnmeldungProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldung_ID', models.IntegerField(db_index=True)),
                ('school_ID', models.IntegerField(db_index=True)),
                ('lernzeit_ID', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('stunde', models.IntegerField(db_index=True)),
            ],
        ),
    ]
