# Generated by Django 5.1.5 on 2025-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_anmeldungprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='anmeldungprofile',
            name='lz_date',
            field=models.DateField(db_index=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
