# Generated by Django 5.1.5 on 2025-02-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_anmeldungprofile_lz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anmeldungprofile',
            name='lz_date',
            field=models.DateField(db_index=True, default='2021-01-01'),
        ),
    ]
