# Generated by Django 5.1.5 on 2025-02-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture',
        ),
    ]
