# Generated by Django 5.1.5 on 2025-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_remove_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
