# Generated by Django 5.1.5 on 2025-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_remove_studentprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
