# Use a base image
FROM ubuntu:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3 \
    python3-pip \
    && apt-get clean

RUN pip install Celery --break-system-packages

# Clone the public repository
WORKDIR /app
COPY ./setup.sh /app/docker/setup.sh

# Copy the start_services.sh script into the container
RUN chmod +x /app/docker/*.sh

# Default command
CMD ["/bin/bash", "/app/start_services.sh"]
