networks:
  lernplan_network:
    driver: bridge

services:
  app:
    build:
      context: .
    image: gamesluk/lernplan:latest
    container_name: lernplan_app
    networks:
      - lernplan_network
    volumes:
      - ./Lernplan:/app
    command: ["/bin/bash", "-c", "/app/docker/setup.sh && /bin/bash"]

  redis:
    image: redis:latest
    container_name: lernplan_redis
    networks:
      - lernplan_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: lernplan_cloudflared
    networks:
      - lernplan_network
    volumes:
      - ./Lernplan/docker/cloudflared/:/etc/cloudflared/:ro # Mount der Config-Datei
    command: tunnel --loglevel debug --config /etc/cloudflared/config.yml run lernplan-tunnel