# Generated by Django 5.1.5 on 2025-01-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
