# Generated by Django 5.1.5 on 2025-01-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ID', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('profile_picture', models.BinaryField(blank=True, db_index=True, null=True)),
                ('teams', models.JSONField(db_index=True, default=list)),
                ('klasse', models.CharField(db_index=True, max_length=1)),
                ('stufe', models.IntegerField(db_index=True)),
            ],
        ),
    ]
